const wordList = [
    "apple",
    "banana",
    "cherry",
    "date",
    "elderberry",
    "fig",
    "grape",
    "honeydew",
    "ice cream",
    "jackfruit",
    "kiwi",
    "lemon",
    "mango",
    "nectarine",
    "orange",
    "papaya",
    "quince",
    "raspberry",
    "strawberry",
    "tangerine",
    "ugli fruit",
    "victoria plum",
    "watermelon",
    "xigua",
    "yellow passionfruit",
    "zucchini",
    "acre",
    "act",
    "actor",
    "actress",
    "add",
    "address",
    "adult",
    "advantage",
    "afraid",
    "after",
    "afternoon",
    "again",
    "against",
    "age",
    "agency",
    "agent",
    "ago",
    "agree",
    "agreement",
    "ahead",
    "air",
    "aircraft",
    "airline",
    "airplane",
    "airport",
    "ajar",
    "alarm",
    "album",
    "alcohol",
    "alive",
    "all",
    "alley",
    "allow",
    "almost",
    "alone",
    "along",
    "already",
    "also",
    "alter",
    "alternative",
    "although",
    "always",
    "ambulance",
    "american",
    "amount",
    "analysis",
    "analyst",
    "ancient",
    "and",
    "angel",
    "angle",
    "angry",
    "animal",
    "announce",
    "annual",
    "another",
    "answer",
    "antenna",
    "antique",
    "anxiety",
    "any",
    "apart",
    "apartment",
    "apparent",
    "apple",
    "application",
    "appoint",
    "appliance",
    "approve",
    "approval",
    "April",
    "arch",
    "architect",
    "architecture",
    "area",
    "argue",
    "argument",
    "arm",
    "army",
    "around",
    "arrange",
    "arrival",
    "art",
    "article",
    "artist",
    "artwork",
    "ask",
    "aspect",
    "assessment",
    "asset",
    "assign",
    "assistance",
    "assistant",
    "associate",
    "association",
    "assume",
    "asthma",
    "athlete",
    "atom",
    "attack",
    "attempt",
    "attention",
    "attitude",
    "attract",
    "attraction",
    "author",
    "authority",
    "auto",
    "automatic",
    "automotive",
    "availability",
    "average",
    "award",
    "aware",
    "away",
    "awesome",
    "baby",
    "bachelor",
    "back",
    "background",
    "bad",
    "bag",
    "balance",
    "ball",
    "bamboo",
    "banana",
    "band",
    "bank",
    "bar",
    "bare",
    "barrel",
    "base",
    "baseball",
    "basic",
    "basis",
    "basket",
    "bath",
    "battery",
    "be",
    "beach",
    "bean",
    "bear",
    "beauty",
    "because",
    "become",
    "beef",
    "before",
    "begin",
    "behavior",
    "behind",
    "being",
    "believe",
    "below",
    "belt",
    "bench",
    "benefit",
    "best",
    "bet",
    "better",
    "between",
    "beyond",
    "bicycle",
    "bid",
    "bike",
    "bind",
    "biology",
    "bird",
    "birth",
    "bit",
    "bite",
    "bitter",
    "black",
    "blade",
    "blame",
    "blanket",
    "blast",
    "bleed",
    "blind",
    "block",
    "blood",
    "blow",
    "blue",
    "board",
    "boat",
    "body",
    "boil",
    "bomb",
    "bone",
    "bonus",
    "book",
    "boost",
    "border",
    "borrow",
    "boss",
    "bottom",
    "bounce",
    "box",
    "boy",
    "bracket",
    "brain",
    "brand",
    "bread",
    "break",
    "breast",
    "breath",
    "brick",
    "bridge",
    "brief",
    "bright",
    "bring",
    "brush",
    "bubble",
    "budget",
    "buffalo",
    "build",
    "bulb",
    "bulk",
    "bullet",
    "bundle",
    "bunker",
    "burden",
    "bureau",
    "burger",
    "burst",
    "bus",
    "business",
    "busy",
    "but",
    "butter",
    "button",
    "buy",
    "cabbage",
    "cable",
    "cactus",
    "cage",
    "cake",
    "calculate",
    "calcium",
    "call",
    "calm",
    "camera",
    "camp",
    "campaign",
    "can",
    "cancel",
    "cancer",
    "candidate",
    "cap",
    "capability",
    "capital",
    "captain",
    "car",
    "carbon",
    "card",
    "cargo",
    "carpet",
    "carry",
    "case",
    "cash",
    "cast",
    "cat",
    "catch",
    "category",
    "cattle",
    "cause",
    "caution",
    "cave",
    "cd",
    "ceiling",
    "celebrate",
    "cell",
    "cellular",
    "cent",
    "center",
    "central",
    "century",
    "ceramic",
    "certain",
    "certificate",
    "chair",
    "chalk",
    "champion",
    "change",
    "channel",
    "charge",
    "check",
    "cheese",
    "chef",
    "cherry",
    "chest",
    "chicken",
    "chief",
    "child",
    "chili",
    "china",
    "chip",
    "chocolate",
    "choice",
    "choose",
    "chronic",
    "chuckle",
    "chunk",
    "church",
    "cigarette",
    "circle",
    "citizen",
    "city",
    "civil",
    "claim",
    "clap",
    "clarify",
    "claw",
    "clay",
    "clean",
    "clear",
    "clerk",
    "client",
    "cliff",
    "climate",
    "climb",
    "clinic",
    "clip",
    "clock",
    "clog",
    "close"
];

const chosenWord = wordList[Math.floor(Math.random() * wordList.length)];
const wordDisplay = document.getElementById("word-display");
const guessesElement = document.getElementById("guesses");
const keyboard = document.querySelector(".keyboard");

let guesses = 7;
let guessedLetters = [];

function displayWord() {
    let word = "";
    for (let i = 0; i < chosenWord.length; i++) {
        if (guessedLetters.includes(chosenWord[i])) {
            word += chosenWord[i];
        } else {
            word += "_";
        }
    }
    wordDisplay.innerHTML = word;
}

function updateGuesses() {
    guessesElement.innerHTML = guesses;
}

function addLetterToGuessedLetters(letter) {
    if (!guessedLetters.includes(letter)) {
        guessedLetters.push(letter);
    }
}

function checkWin(guessedWord, chosenWord, wordList) {
    if (wordList.includes(chosenWord) && guessedWord === chosenWord) {
      alert("Congratulations, you won!");
      location.reload();
      return true;
    }
    return false;
  }

function handleKeyPress(event) {
    const letter = event.target.innerText;
    addLetterToGuessedLetters(letter);
    if (!chosenWord.includes(letter)) {
        guesses--;
    }
    displayWord();
    updateGuesses();
    if (guesses === 0) {
        alert("Game over, the word was " + chosenWord);
    }
    if (checkWin()) {
        keyboard.style.display = "none";
    }
}

function createKeyboard() {
    const alphabet = "abcdefghijklmnopqrstuvwxyz";
    for (let i = 0; i < alphabet.length; i++) {
        const button = document.createElement("button");
        button.innerText = alphabet[i];
        button.addEventListener("click", handleKeyPress);
        keyboard.appendChild(button);
    }
}

createKeyboard();
displayWord();
updateGuesses();